version: "3.8"

services:

  backend:
    image: python:3.10
    volumes:
      - ./backend/server:/app
    working_dir: /app
    p
    command: bash -c "pip install /app/crewai-0.118.0.tar.gz && pip install -r requirements.txt && python main.py"
    ports:
      - "1500:1500"
    tty: true
    environment:
      OPENAI_MODEL_NAME: ${OPENAI_MODEL_NAME}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OLLAMA_API_KEY: ${OLLAMA_API_KEY}
      OPENWEBUI_API_KEY: ${OPENWEBUI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: stylegen
      POSTGRES_PASSWORD: stylegen
      POSTGRES_DB: main
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
    environment:
      POSTGRES_USER: stylegen
      POSTGRES_PASSWORD: stylegen
      POSTGRES_DB: main
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: stylegen
      POSTGRES_DB: main
      POSTGRES_HOST_AUTH_METHOD: trust